# What are the total number of deaths in each Continent?
### What are the top 5 countries for most deaths in each continent?
### What are the top 5 countries for most reported cases in each continent?
### What are the total number of reported cases and deaths in each continent (a comparison of cases and deaths)?
- Clean-up total_deaths column
- Calculate number of deaths by Continent
- Calculate Death percentage
- Plot final calculations

In [15]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("bolkonsky/covid19")

print("Path to dataset files:", path)

Path to dataset files: /Users/macbook/.cache/kagglehub/datasets/bolkonsky/covid19/versions/1

In [16]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt
import seaborn as sns

path = 'owid-covid-data.csv'
df = pd.read_csv(path)
df.copy()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,new_tests,total_tests,total_tests_per_thousand,new_tests_per_thousand,new_tests_smoothed,new_tests_smoothed_per_thousand,tests_per_case,positive_rate,tests_units,stringency_index,population,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,AFG,Asia,Afghanistan,2019-12-31,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
1,AFG,Asia,Afghanistan,2020-01-01,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
2,AFG,Asia,Afghanistan,2020-01-02,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
3,AFG,Asia,Afghanistan,2020-01-03,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
4,AFG,Asia,Afghanistan,2020-01-04,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44780,NaN,NaN,International,2020-09-15,696.0,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44781,NaN,NaN,International,2020-09-16,696.0,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44782,NaN,NaN,International,2020-09-17,696.0,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44783,NaN,NaN,International,2020-09-18,696.0,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44784,NaN,NaN,International,2020-09-19,696.0,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df['date'] = pd.to_datetime(df['date'])

In [30]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', None)

df.head(1000)

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,new_tests,total_tests,total_tests_per_thousand,new_tests_per_thousand,new_tests_smoothed,new_tests_smoothed_per_thousand,tests_per_case,positive_rate,tests_units,stringency_index,population,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,AFG,Asia,Afghanistan,2019-12-31,0,0.0,NaN,0,0.0,NaN,0.000,0.000,NaN,0.000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
1,AFG,Asia,Afghanistan,2020-01-01,0,0.0,NaN,0,0.0,NaN,0.000,0.000,NaN,0.000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
2,AFG,Asia,Afghanistan,2020-01-02,0,0.0,NaN,0,0.0,NaN,0.000,0.000,NaN,0.000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
3,AFG,Asia,Afghanistan,2020-01-03,0,0.0,NaN,0,0.0,NaN,0.000,0.000,NaN,0.000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
4,AFG,Asia,Afghanistan,2020-01-04,0,0.0,NaN,0,0.0,NaN,0.000,0.000,NaN,0.000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,AGO,Africa,Angola,2020-06-06,86,0.0,1.286,4,0.0,0.0,2.617,0.000,0.039,0.122,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.78,32866268.0,23.890,16.8,2.405,1.362,5819.495,NaN,276.045,3.94,NaN,NaN,26.664,NaN,61.15,0.581
996,AGO,Africa,Angola,2020-06-07,86,0.0,0.286,4,0.0,0.0,2.617,0.000,0.009,0.122,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.78,32866268.0,23.890,16.8,2.405,1.362,5819.495,NaN,276.045,3.94,NaN,NaN,26.664,NaN,61.15,0.581
997,AGO,Africa,Angola,2020-06-08,91,5.0,0.714,4,0.0,0.0,2.769,0.152,0.022,0.122,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.93,32866268.0,23.890,16.8,2.405,1.362,5819.495,NaN,276.045,3.94,NaN,NaN,26.664,NaN,61.15,0.581
998,AGO,Africa,Angola,2020-06-09,92,1.0,0.857,4,0.0,0.0,2.799,0.030,0.026,0.122,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.93,32866268.0,23.890,16.8,2.405,1.362,5819.495,NaN,276.045,3.94,NaN,NaN,26.664,NaN,61.15,0.581
999,AGO,Africa,Angola,2020-06-10,96,4.0,1.429,4,0.0,0.0,2.921,0.122,0.043,0.122,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.93,32866268.0,23.890,16.8,2.405,1.362,5819.495,NaN,276.045,3.94,NaN,NaN,26.664,NaN,61.15,0.581

In [19]:
# df_continent_asia = df[df['continent'] == 'Asia']
# df_continent_asia

In [20]:
df_continents = df.continent.unique().tolist()

In [21]:
df_continents = df.continent.dropna().to_frame()
df_continents

      continent
0          Asia
1          Asia
2          Asia
3          Asia
4          Asia
...         ...
44252    Africa
44253    Africa
44254    Africa
44255    Africa
44256    Africa

[44257 rows x 1 columns]

In [22]:
# continent_dfs = {}

# df_continent_list = df.continent.unique().tolist()
# for cont in df_continent_list:
#     temp_df = df[df['continent'] == cont]
    
#     continent_dfs[cont] = temp_df
    
# print(continent_dfs['South America'].head())

In [23]:
df['continent'].unique().tolist()

['Asia', 'Europe', 'Africa', 'North America', 'South America', 'Oceania', nan]

In [24]:
df['total_deaths'] = df['total_deaths'].fillna(0).astype(int)

In [25]:
df['total_cases'] = df['total_cases'].fillna(0).astype(int)
df

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,new_tests,total_tests,total_tests_per_thousand,new_tests_per_thousand,new_tests_smoothed,new_tests_smoothed_per_thousand,tests_per_case,positive_rate,tests_units,stringency_index,population,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,AFG,Asia,Afghanistan,2019-12-31,0,0.0,NaN,0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
1,AFG,Asia,Afghanistan,2020-01-01,0,0.0,NaN,0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
2,AFG,Asia,Afghanistan,2020-01-02,0,0.0,NaN,0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
3,AFG,Asia,Afghanistan,2020-01-03,0,0.0,NaN,0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
4,AFG,Asia,Afghanistan,2020-01-04,0,0.0,NaN,0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44780,NaN,NaN,International,2020-09-15,696,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44781,NaN,NaN,International,2020-09-16,696,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44782,NaN,NaN,International,2020-09-17,696,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44783,NaN,NaN,International,2020-09-18,696,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44784,NaN,NaN,International,2020-09-19,696,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
df['location'].unique().tolist()

['Afghanistan',
 'Albania',
 'Algeria',
 'Andorra',
 'Angola',
 'Anguilla',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Bonaire Sint Eustatius and Saba',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'British Virgin Islands',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Cayman Islands',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo',
 'Costa Rica',
 "Cote d'Ivoire",
 'Croatia',
 'Cuba',
 'Curacao',
 'Cyprus',
 'Czech Republic',
 'Democratic Republic of Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Ethiopia',
 'Faeroe Islands',
 'Falkland Islands',
 'Fiji',
 'Finland',
 'France',
 'French Polynesia',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Greece',
 'Greenland',
 'Grenada',
 'Guam',
 'Guatemala',
 'Guernsey',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hong Kong',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Isle of Man',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jersey',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kosovo',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Macedonia',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Montserrat',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'Northern Mariana Islands',
 'Norway',
 'Oman',
 'Pakistan',
 'Palestine',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Romania',
 'Russia',
 'Rwanda',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Vincent and the Grenadines',
 'San Marino',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Sint Maarten (Dutch part)',
 'Slovakia',
 'Slovenia',
 'Somalia',
 'South Africa',
 'South Korea',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syria',
 'Taiwan',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Timor',
 'Togo',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turks and Caicos Islands',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'United States Virgin Islands',
 'Uruguay',
 'Uzbekistan',
 'Vatican',
 'Venezuela',
 'Vietnam',
 'Western Sahara',
 'Yemen',
 'Zambia',
 'Zimbabwe',
 'World',
 'International']

In [27]:
df_continent_country = df.groupby(['continent', 'location'])[['total_cases', 'total_deaths']].sum()
df_continent_country = df_continent_country.reset_index()
df_continent_country

,continent,location,total_cases,total_deaths
0,Africa,Algeria,3333579,153685
1,Africa,Angola,141005,6076
2,Africa,Benin,174587,3155
3,Africa,Botswana,95560,394
4,Africa,Burkina Faso,167562,8467
5,Africa,Burundi,34545,158
6,Africa,Cameroon,1847411,44009
7,Africa,Cape Verde,272962,2776
8,Africa,Central African Republic,448097,5248
9,Africa,Chad,117021,9606
10,Africa,Comoros,37867,710
11,Africa,Congo,320916,6604
12,Africa,Cote d'Ivoire,1537861,10615
13,Africa,Democratic Republic of Congo,949285,23771
14,Africa,Djibouti,619144,6176
15,Africa,Egypt,9314000,465690
16,Africa,Equatorial Guinea,406042,6457
17,Africa,Eritrea,28289,0
18,Africa,Ethiopia,2522323,40974
19,Africa,Gabon,768108,5259
20,Africa,Gambia,121733,3778
21,Africa,Ghana,3500181,20048
22,Africa,Guinea,871820,5270
23,Africa,Guinea-Bissau,236128,3018
24,Africa,Kenya,2085434,37573
25,Africa,Lesotho,58251,1536
26,Africa,Liberia,119308,7627
27,Africa,Libya,694806,12500
28,Africa,Madagascar,948836,10787
29,Africa,Malawi,362775,10090
30,Africa,Mali,295246,14892
31,Africa,Mauritania,574338,14958
32,Africa,Mauritius,57971,1688
33,Africa,Morocco,3838966,72566
34,Africa,Mozambique,242696,1531
35,Africa,Namibia,338321,2939
36,Africa,Niger,164022,9606
37,Africa,Nigeria,4329380,92150
38,Africa,Rwanda,243200,855
39,Africa,Sao Tome and Principe,94397,1748
40,Africa,Senegal,1134757,21006
41,Africa,Seychelles,10334,0
42,Africa,Sierra Leone,200786,7871
43,Africa,Somalia,380734,12038
44,Africa,South Africa,42609907,845136
45,Africa,South Sudan,251682,4528
46,Africa,Sudan,1254401,77745
47,Africa,Swaziland,278135,4861
48,Africa,Tanzania,76256,3103
49,Africa,Togo,114625,2781
50,Africa,Tunisia,312065,9124
51,Africa,Uganda,191855,1325
52,Africa,Western Sahara,60086,113
53,Africa,Zambia,680183,16405
54,Africa,Zimbabwe,356838,9132
55,Asia,Afghanistan,3941214,121942
56,Asia,Armenia,3879870,72442
57,Asia,Azerbaijan,3005582,41579
58,Asia,Bahrain,4394488,14685
59,Asia,Bangladesh,24219177,324841
60,Asia,Bhutan,14135,0
61,Asia,Brunei,25762,385
62,Asia,Cambodia,31165,0
63,Asia,China,18913282,924779
64,Asia,Georgia,169007,2218
65,Asia,Hong Kong,0,0
66,Asia,India,211519927,4198752
67,Asia,Indonesia,12526095,584114
68,Asia,Iran,38261881,2103573
69,Asia,Iraq,14047576,462683
70,Asia,Israel,8498679,75067
71,Asia,Japan,5095434,147275
72,Asia,Jordan,196032,1823
73,Asia,Kazakhstan,8939744,98879
74,Asia,Kuwait,7407673,50214
75,Asia,Kyrgyzstan,2849491,82657
76,Asia,Laos,3349,0
77,Asia,Lebanon,888728,10897
78,Asia,Malaysia,1370983,19647
79,Asia,Maldives,529909,2025
80,Asia,Mongolia,33001,0
81,Asia,Myanmar,83447,1248
82,Asia,Nepal,2527851,11222
83,Asia,Oman,7030732,44480
84,Asia,Pakistan,28295571,593914
85,Asia,Palestine,1686513,9797
86,Asia,Philippines,12793480,275906
87,Asia,Qatar,12559424,17335
88,Asia,Saudi Arabia,28504586,297137
89,Asia,Singapore,6457862,3874
90,Asia,South Korea,2608946,50803
91,Asia,Sri Lanka,325567,1718
92,Asia,Syria,136534,5903
93,Asia,Taiwan,81477,1213
94,Asia,Tajikistan,820133,7425
95,Asia,Thailand,547959,9392
96,Asia,Timor,3859,0
97,Asia,Turkey,31708204,798231
98,Asia,United Arab Emirates,7289747,45186
99,Asia,Uzbekistan,2680074,17488
100,Asia,Vietnam,89780,1268
101,Asia,Yemen,167603,46564
102,Europe,Albania,642140,19086
103,Europe,Andorra,153245,8215
104,Europe,Austria,3422980,110162
105,Europe,Belarus,8180154,62812
106,Europe,Belgium,10927830,1505454
107,Europe,Bosnia and Herzegovina,1341722,44417
108,Europe,Bulgaria,1214336,47305
109,Europe,Croatia,764050,19864
110,Europe,Cyprus,180229,3040
111,Europe,Czech Republic,2436975,55401
112,Europe,Denmark,2155965,93549
113,Europe,Estonia,339864,9821
114,Europe,Faeroe Islands,42882,0
115,Europe,Finland,1135361,48026
116,Europe,France,31237297,4666048
117,Europe,Germany,33243573,1354114
118,Europe,Gibraltar,32351,0
119,Europe,Greece,826212,32451
120,Europe,Guernsey,42110,2060
121,Europe,Hungary,765327,84191
122,Europe,Iceland,329846,1665
123,Europe,Ireland,4072205,255811
124,Europe,Isle of Man,54645,3590
125,Europe,Italy,40735797,5583789
126,Europe,Jersey,53777,4567
127,Europe,Kosovo,872666,28733
128,Europe,Latvia,190176,4221
129,Europe,Liechtenstein,15787,168
130,Europe,Lithuania,331054,11433
131,Europe,Luxembourg,878328,18086
132,Europe,Macedonia,1149072,51353
133,Europe,Malta,150570,1347
134,Europe,Moldova,2946193,88771
135,Europe,Monaco,14813,162
136,Europe,Montenegro,317906,5933
137,Europe,Netherlands,8721846,948475
138,Europe,Norway,1554349,38955
139,Europe,Poland,5996661,221955
140,Europe,Portugal,6860575,242133
141,Europe,Romania,6513415,313542
142,Europe,Russia,96170811,1488491
143,Europe,San Marino,112823,7336
144,Europe,Serbia,2961839,64847
145,Europe,Slovakia,368616,4438
146,Europe,Slovenia,333091,17946
147,Europe,Spain,49782077,4545805
148,Europe,Sweden,9336682,788096
149,Europe,Switzerland,5819299,267037
150,Europe,Ukraine,8959634,210428
151,Europe,United Kingdom,43905934,5976232
152,Europe,Vatican,1978,0
153,North America,Anguilla,524,0
154,North America,Antigua and Barbuda,9448,478
155,North America,Aruba,95093,762
156,North America,Bahamas,104948,3092
157,North America,Barbados,19012,1111
158,North America,Belize,41508,701
159,North America,Bermuda,23410,1361
160,North America,Bonaire Sint Eustatius and Saba,1641,5
161,North America,British Virgin Islands,2475,153
162,North America,Canada,15884203,1172086
163,North America,Cayman Islands,26702,183
164,North America,Costa Rica,2240293,21678
165,North America,Cuba,410616,13136
166,North America,Curacao,5997,177
167,North America,Dominica,3111,0
168,North America,Dominican Republic,7214853,145156
169,North America,El Salvador,1690781,46105
170,North America,Greenland,2237,0
171,North America,Grenada,3739,0
172,North America,Guatemala,4839978,182725
173,North America,Haiti,759479,17051
174,North America,Honduras,4169504,129049
175,North America,Jamaica,168783,2195
176,North America,Mexico,44399655,4906769
177,North America,Montserrat,1993,147
178,North America,Nicaragua,368860,11874
179,North America,Panama,6919894,150142
180,North America,Puerto Rico,2094623,34448
181,North America,Saint Kitts and Nevis,2680,0
182,North America,Saint Lucia,3604,0
183,North America,Saint Vincent and the Grenadines,5897,0
184,North America,Sint Maarten (Dutch part),27843,2495
185,North America,Trinidad and Tobago,85414,2124
186,North America,Turks and Caicos Islands,23784,306
187,North America,United States,523436049,20194934
188,North America,United States Virgin Islands,59134,1238
189,Oceania,Australia,2198194,38504
190,Oceania,Fiji,3782,72
191,Oceania,French Polynesia,28892,16
192,Oceania,Guam,78585,1186
193,Oceania,New Caledonia,3691,0
194,Oceania,New Zealand,208315,3395
195,Oceania,Northern Mariana Islands,5569,336
196,Oceania,Papua New Guinea,19604,208
197,South America,Argentina,23216586,480444
198,South America,Bolivia,7779665,336600
199,South America,Brazil,278829506,9969586
200,South America,Chile,37214626,895847
201,South America,Colombia,34855931,1139396
202,South America,Ecuador,10208880,733100
203,South America,Falkland Islands,2077,0
204,South America,Guyana,75159,3157
205,South America,Paraguay,952558,15122
206,South America,Peru,50207019,2039742
207,South America,Suriname,210740,3827
208,South America,Uruguay,175346,4628
209,South America,Venezuela,2520362,21473

In [28]:
df_continent = df.groupby('continent')[['total_cases', 'total_deaths']].sum().reset_index()
df_continent

       continent  total_cases  total_deaths
0         Africa     90226617       2140158
1           Asia    517161533      11580581
2         Europe    398597068      29361361
3  North America    615147765      27041681
4        Oceania      2546632         43717
5  South America    446248455      15642922